---
# handlers file for ansible-nfs-server
- name: restart nfs-kernel-server
  service:
    name: "nfs-kernel-server"
    state: "restarted"
    enabled: true
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: restart nfs-server
  service:
    name: "nfs-server"
    state: "restarted"
    enabled: true
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
